<?php $collectionData = $block->getCollectModel(); 
 ?>
<table>
    <tr>
        <th> Id </th>
        <th> Name </th>
        <th> Message </th>
        <th> email </th>
    </tr>
    <tbody>
        <?php foreach ($collectionData as $item) : ?>
        <tr>
            <td>
                <?php echo $item['id']; ?>
            </td>
            <td>
                <?php echo $item['name']; ?>
            </td>
            <td>
                <?php echo $item['message']; ?>
            </td>
            <td>
                <?php echo $item['email']; ?>
            </td>
            <td>
                <a href="<?php echo $block->getDeleteUrl($item['id']); ?>">
                    <?php echo __('Delete Item') ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $block->getEditUrl($item['id']); ?>">
                    <?php echo __('Edit') ?>
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div>
    <a href="<?php echo $block->getAddUrl($item['id']); ?>">
        <?php echo __('ADD DATA') ?>
    </a>
</div>