<?php 
$data = $block->getRowData();
extract($data);
?>
<div class="block block-customer-login">
    <div class="block-title">
        <h2><?php echo __('Add Data'); ?></h2>
    </div>
    <div class="block-content" aria-labelledby="block-heading">
        <form class="form"
              action=""
              method="post"
              id="edit-form"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">

                <div class="field id required">
                    <label class="label" for="id"><span><?php /* @escapeNotVerified */ echo __('Id') ?></span></label>
                    <div class="control">
                        <input name="data[id]" id="id" type="text" class="input-text" title="<?php echo __('Id') ?>" value="<?php echo $id; ?>">
                    </div>
                </div>

                <div class="field title required">
                    <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
                    <div class="control">
                        <input name="data[name]" id="name" type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" data-validate="{required:true}" value="<?php echo $name; ?>">
                    </div>
                </div>
                <div class="field title required">
                    <label class="label" for="message"><span><?php /* @escapeNotVerified */ echo __('Message') ?></span></label>
                    <div class="control">
                        <input name="data[message]" id="message" type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('message') ?>" data-validate="{required:true}" value="<?php echo $message; ?>">
                    </div>
                </div>
                <div class="field title required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                    <div class="control">
                        <input name="data[email]" id="email" type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true}" value="<?php echo $email; ?>">
                    </div>
                </div>

                            <div class="actions-toolbar">
                    <div class="primary"><input type="submit" class="action login primary" name="data[submit]" id="send2" value="<?php echo __('Save') ?>"></div>
                
                </div>
                <div>
                <a href="">
                <?php echo __('Return back') ?></a>
</div>
            </fieldset>
        </form>
    </div>
</div>
